types:
  TorchModule: torch.nn:Module
  Path: pathlib:Path
  AugmentationPipeline: albumentations:Compose
  Dataloader: torch.utils.data:DataLoader
  Blend: ./src/generator/blends.py:Blend
  Callback: ./src/training/callbacks.py:Callback
  EarlyStoppingCallback: ./src/training/callbacks.py:EarlyStoppingCallback

schema:
  seed: int
  device: str

  wandb_entity: str
  wandb_project: str
  wandb_run_name: str

  num_epochs: int
  eval_freq: int
  image_size: int

  use_mixed_precision: bool
  compile_model: bool

  generator: ./src/generator/generator.py:LogoDatasetGenerator
  model: TorchModule
  optim: torch.optim:Optimizer
  scheduler: torch.optim.lr_scheduler:LRScheduler
  train_loader: Dataloader
  val_loader: Dataloader
  criterion: TorchModule
  metrics: ./src/training/metrics.py:MetricCollection
  callbacks: list[Callback]

  vit_config:
    img_size: int
    patch_size: int
    in_channels: int
    embed_dim: int
    depth: int
    num_heads: int
    mlp_ratio: float
    ls_init_value: float
    num_register_tokens: int

  generator_config:
    logos_dir: Path
    backgrounds_dir: Path
    output_size: list[int]
    length: int
    negative_ratio: float
    seed: int
    max_retries: int
    blends: list[Blend]
    same_scene_blend_variants: bool
    logo_transform: AugmentationPipeline
    composition_transform: AugmentationPipeline
