# This file was auto-generated by ezconfy. Do not edit manually.
from albumentations.core.composition import Compose
from pathlib import Path
from pydantic import BaseModel, ConfigDict, Field
from src.generator.blends import Blend
from src.generator.generator import LogoDatasetGenerator
from src.training.callbacks import Callback
from src.training.metrics import MetricCollection
from torch.nn.modules.module import Module
from torch.optim.lr_scheduler import LRScheduler
from torch.optim.optimizer import Optimizer
from torch.utils.data.dataloader import DataLoader


class VitConfig(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    img_size: int = Field(...)
    patch_size: int = Field(...)
    in_channels: int = Field(...)
    embed_dim: int = Field(...)
    depth: int = Field(...)
    num_heads: int = Field(...)
    mlp_ratio: float = Field(...)
    ls_init_value: float = Field(...)
    num_register_tokens: int = Field(...)


class GeneratorConfig(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    logos_dir: Path = Field(...)
    backgrounds_dir: Path = Field(...)
    output_size: list[int] = Field(...)
    length: int = Field(...)
    negative_ratio: float = Field(...)
    seed: int = Field(...)
    max_retries: int = Field(...)
    blends: list[Blend] = Field(...)
    same_scene_blend_variants: bool = Field(...)
    logo_transform: Compose = Field(...)
    composition_transform: Compose = Field(...)


class ConfigModel(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    seed: int = Field(...)
    device: str = Field(...)
    wandb_entity: str = Field(...)
    wandb_project: str = Field(...)
    wandb_run_name: str = Field(...)
    num_epochs: int = Field(...)
    eval_freq: int = Field(...)
    image_size: int = Field(...)
    use_mixed_precision: bool = Field(...)
    generator: LogoDatasetGenerator = Field(...)
    model: Module = Field(...)
    optim: Optimizer = Field(...)
    scheduler: LRScheduler = Field(...)
    train_loader: DataLoader = Field(...)
    val_loader: DataLoader = Field(...)
    criterion: Module = Field(...)
    metrics: MetricCollection = Field(...)
    callbacks: list[Callback] = Field(...)
    vit_config: VitConfig = Field(...)
    generator_config: GeneratorConfig = Field(...)
